items/urls.py
from django.urls import path, include
from . import views
urlpatterns = [
    #跳转页面
    path('create/', views.testone),

    #项目创建
    path('api/create/', views.item_create),

]

vin码查询/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path
from indexpage.views import index_page


urlpatterns = [
    url(r'^jet/', include('jet.urls', 'jet')),
    url(r'^$', index_page),
    url(r'^vin_search/', include('vin_search.urls')),
    # url(r'^admin/users/myuser/add/', include('users.urls')),
    url(r'^admin/', admin.site.urls),
    #开产品和项目
    path('product/', include('product.urls')),
    #项目录入
    path('items/', include('items.urls'))


]

indexpage/models.py
from django.db import models

# Create your models here.

class Notice(models.Model):
    message = models.CharField(max_length=1000, verbose_name="消息内容")
    class Meta:
        verbose_name = u'  通知消息'
        verbose_name_plural = verbose_name
    def __str__(self):
        """重载函数，使自定义字符串能打印"""
        return self.message

store/models.py

from django.db import models

# Create your models here.
from organization.models import LastStore
from users.models import MyUser


class Customer(models.Model):

    state_tuple = (
        (0, u'未到店'),
        (1, u'已到店'),
        (2, u'新单'),
        (3, u'已完成'),
    )
    age_tuple = (
        (0, u'男'),
        (1, u'女'),
        (999, u'请选择'),
    )

    channel_tuple = (
        (0,u'抖音'),
        (1,u'微博'),
        (2,u'团购'),
        (999, u'请选择'),
    )

    constellation_tuple = (
        (0, u'白羊座'),
        (1, u'金牛座'),
        (2, u'双子座'),
        (3, u'巨蟹座'),
        (4, u'狮子座'),
        (5, u'处女座'),
        (6, u'天秤座'),
        (7, u'天蝎座'),
        (8, u'射手座'),
        (9, u'摩羯座'),
        (10, u'水瓶座'),
        (11, u'双鱼座'),
        (999, u'请选择')

    )

    is_from_web = models.BooleanField(verbose_name="是否由网络客服录入", default=True, editable=False)

    name = models.CharField(max_length=20, verbose_name="姓名", null=True)
    phone = models.CharField(max_length=20, verbose_name="手机号")
    phone1 = models.CharField(max_length=20, verbose_name="手机号2", null=True, blank=True)
    note = models.TextField(verbose_name="咨询备注", null=True, blank=True)
    state = models.IntegerField(choices=state_tuple, verbose_name="赴约状态", default=0)
    store = models.ForeignKey(LastStore, verbose_name="门店", related_name='web_staff', on_delete=models.DO_NOTHING, null=True, blank=True)
    web_staff = models.ForeignKey(MyUser, verbose_name="网络客服", related_name='web_staff', on_delete=models.DO_NOTHING, null=True, blank=True)
    sex = models.IntegerField(choices=age_tuple, verbose_name="性别", default=999,null=True ,blank=True)
    age = models.CharField(max_length=20, verbose_name="年龄", default='', blank=True)
    constellation = models.IntegerField(choices=constellation_tuple, verbose_name="星座", default=999, blank=True)
    address = models.CharField(max_length=50, verbose_name="住址", default='', blank=True)
    job = models.CharField(max_length=20, verbose_name="职业", default='', blank=True)
    order_time = models.DateTimeField(verbose_name="预约到店时间", null=True, blank=True)
    ill_place = models.CharField(max_length=50, verbose_name="患病部位", default='', blank=True)
    ill_time = models.CharField(max_length=20, verbose_name="患病时间", default='', blank=True)
    ill_kind = models.CharField(max_length=50, verbose_name="患病种类", default='', blank=True)
    #前台
    front_staff = models.ForeignKey(MyUser, verbose_name="所属前台",  related_name='front_staff',  on_delete=models.DO_NOTHING, null=True, blank=True)
    #美容咨询师
    beauty_consultant = models.ForeignKey(MyUser, verbose_name="分配美容咨询师", related_name='beauty_consultant',  on_delete=models.DO_NOTHING, null=True, blank=True)
    #回访时间
    back_date = models.DateField(verbose_name="回访日期", null=True, blank=True)


    # 新增字段 2018-8-3
    # QQ号码
    qq_num = models.CharField(max_length=20, verbose_name="QQ号码", null=True, blank=True)
    # 预约号
    order_num = models.CharField(max_length=50, verbose_name="预约号", null=True, blank=True)
    # 医院
    hospital = models.CharField(max_length=50, verbose_name="医院", null=True, blank=True)
    # 接待医生
    doctor = models.CharField(max_length=50, verbose_name="接待医生", null=True, blank=True)
    # 登记时间
    register_time = models.DateTimeField(verbose_name="登记时间", null=True, blank=True)

    # 新增字段 2018-8-11
    # 区域
    area = models.CharField(max_length=50, verbose_name="区域", null=True, blank=True)
    back_note = models.CharField(max_length=500, verbose_name="回访备注", null=True, blank=True)

    # 新增字段 2018-8-14
    # 生日
    birthday = models.CharField(max_length=50, verbose_name="生日", null=True, blank=True)
    # 微信
    we_num = models.CharField(max_length=20, verbose_name="微信号码", null=True, blank=True)
    # 客户端
    client = models.CharField(max_length=20, verbose_name="客户端", null=True, blank=True)
    # 渠道
    channel = models.IntegerField(choices=channel_tuple, verbose_name="渠道", default=999, null=True, blank=True)

    # 新增字段

    # 到店时间
    arrive_time = models.DateTimeField(verbose_name="到店时间", null=True, blank=True)


    def __str__(self):
        return self.name
    class Meta:
        verbose_name = "客户信息"
        verbose_name_plural = "客户信息"

indexpage/views.py
from django.shortcuts import render

# Create your views here.
from indexpage.models import Notice
from users.models import MyUser


def index_page(request):
    admin_user = request.user
    back_notice_message = ""
    if(request.user.job == 4):
        num = 0
        back_notice_message = ", 您今天有" + str(num) + "位用户待回访"

    if (request.user.admin_level == 2):
        admin_user = MyUser.objects.get(id=request.user.parent_id)
    message_list = Notice.objects.values_list('message', flat=True)
    context = {
        'admin_user': admin_user,
        'back_notice_message': back_notice_message,
        'message_list': message_list,
    }

    return render(request, 'indexpage/index.html', context)

indexpage/templates/indexpage/index.html
{% extends 'admin/base.html' %}


{% block content %}


      <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/4.1.0/css/bootstrap.min.css">
      <script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
      <script src="https://cdn.bootcss.com/popper.js/1.12.5/umd/popper.min.js"></script>
      <script src="https://cdn.bootcss.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
  <style>
      /* Make the image fully responsive */
      .carousel-inner img {
          width: 100%;
          height: 100%;
      }
  </style>

    <div class="card bg-light text-dark">
        <div class="card-body">欢迎！{{ admin_user.user_org2.get }} {{ request.user.get_job_display }} {{ request.user.name }} {{ back_notice_message }}</div>
    </div>

    <br/>

    <div id="demo" class="carousel slide" data-ride="carousel">

  <!-- 指示符 -->
      <ul class="carousel-indicators">
        <li data-target="#demo" data-slide-to="0" class="active"></li>
        <li data-target="#demo" data-slide-to="1"></li>
        <li data-target="#demo" data-slide-to="2"></li>
      </ul>

      <!-- 轮播图片 -->
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img src="http://static.runoob.com/images/mix/img_fjords_wide.jpg">
        </div>
        <div class="carousel-item">
          <img src="http://static.runoob.com/images/mix/img_nature_wide.jpg">
        </div>
        <div class="carousel-item">
          <img src="http://static.runoob.com/images/mix/img_mountains_wide.jpg">
        </div>
      </div>

  <!-- 左右切换按钮 -->
  <a class="carousel-control-prev" href="#demo" data-slide="prev">
    <span class="carousel-control-prev-icon"></span>
  </a>
  <a class="carousel-control-next" href="#demo" data-slide="next">
    <span class="carousel-control-next-icon"></span>
  </a>

</div>

    <br />
    <div class="alert alert-primary">
     <strong>通知信息</strong>
    <table class="table">

	<tbody>

    {% for message in message_list %}
		<tr>
			<td>{{ message }}</td>
		</tr>
    {% endfor %}
	</tbody>
</table>
    </div>
{% endblock %}